#!/usr/bin/env python3
"""Generate mediamtx.yml from streams.json.

Each stream:
  { "name": "cam1", "source": "rtsp://..." }
    pulled directly from the camera, only while a viewer is connected
    (sourceOnDemand). Works when the camera audio is G.711 or absent.

  { "name": "cam1", "source": "rtsp://...", "transcode_audio": true }
    an ffmpeg process is started on demand (runOnDemand) that copies the
    video and transcodes the audio to Opus, which browsers can play over
    WebRTC. Needed for cameras that only offer AAC audio.

  { "name": "cam1", "source": "rtsp://...", "enabled": false }
    kept in the file but not configured in MediaMTX (disabled camera).

String entries in the array are comments and skipped.

--paths-json: also print the path configurations as JSON on stdout
(used by api/ to live-apply changes through the MediaMTX API).
"""
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
FFMPEG = ROOT / "bin" / "ffmpeg"
PYTHON = shutil.which("python3") or "python3"

TEMPLATE = """# Auto-generated by gen-config.py from streams.json — do not edit.
logLevel: info

rtsp: true
rtspAddress: :8554
rtmp: false
srt: false
moq: false

webrtc: true
webrtcAddress: :8889
webrtcAllowOrigins: ["*"]

hls: false

api: true
apiAddress: 127.0.0.1:9997

paths:
{paths}
"""

# transcode.py wraps ffmpeg with a stall watchdog: an ffmpeg blocked in a
# network read ignores MediaMTX's SIGINT and leaks (frozen camera, WiFi
# drop). The wrapper kills it after 20s without progress.
TRANSCODE_CMD = (
    PYTHON + " {wrapper} {source} "
    "rtsp://127.0.0.1:$RTSP_PORT/$MTX_PATH"
)

NAME_RE = re.compile(r"^[a-zA-Z0-9_-]+$")


def main():
    paths_json = "--paths-json" in sys.argv
    try:
        streams = json.loads((ROOT / "streams.json").read_text())
    except FileNotFoundError:
        sys.exit("streams.json not found — run: cp streams.json.example streams.json (then edit it)")
    except json.JSONDecodeError as e:
        sys.exit(f"streams.json is not valid JSON: {e}")
    if not isinstance(streams, list) or not streams:
        sys.exit("streams.json is empty — add at least one stream")

    lines = []
    confs = {}
    seen = set()
    for i, s in enumerate(streams, 1):
        if isinstance(s, str):
            continue  # string entries are comments
        if not isinstance(s, dict) or "name" not in s or "source" not in s:
            sys.exit(f"entry #{i}: every stream needs both \"name\" and \"source\" keys")
        if s.get("enabled") is False:
            continue  # disabled camera
        name, source = s["name"], s["source"]
        if not NAME_RE.match(name):
            sys.exit(f"invalid stream name {name!r} (use letters, digits, -, _)")
        if name in seen:
            sys.exit(f"duplicate stream name {name!r}")
        seen.add(name)
        if not source.startswith("rtsp://"):
            sys.exit(f"{name}: source must be an rtsp:// URL")

        if s.get("transcode_audio"):
            if not FFMPEG.exists():
                sys.exit(f"{name}: transcode_audio needs {FFMPEG} — run ./setup.sh first")
            cmd = TRANSCODE_CMD.format(wrapper=ROOT / "transcode.py", source=source)
            lines.append(
                f"  {name}:\n"
                f"    runOnDemand: {cmd}\n"
                f"    runOnDemandRestart: yes\n"
                f"    runOnDemandCloseAfter: 10s"
            )
            confs[name] = {
                "runOnDemand": cmd,
                "runOnDemandRestart": True,
                "runOnDemandCloseAfter": "10s",
            }
        else:
            # sourceOnDemand: pull the camera only while a viewer is connected
            lines.append(f"  {name}:\n    source: {source}\n    sourceOnDemand: yes")
            confs[name] = {"source": source, "sourceOnDemand": True}

    (ROOT / "mediamtx.yml").write_text(TEMPLATE.format(paths="\n".join(lines)))
    if paths_json:
        print(json.dumps(confs))
        print(f"mediamtx.yml written with {len(lines)} stream(s)", file=sys.stderr)
    else:
        print(f"mediamtx.yml written with {len(lines)} stream(s)")


if __name__ == "__main__":
    main()
